### ISSUE TITLE
Broken construction wands/vein mine

### ISSUE THREAD

**Issue by AsterOni** [AbdulMuqsit/Starpack-Aleph#79]
when holding bound key for vein mine, the highight for blocks are misshapen and incorrect. this problem also occurs with the construction wand, and will place down blocks randomly.

**Comment by starmun-0010** [comment]
### To Reproduce
Teleport to coordinate (100000, y, 100000)
Hold any construction wand in hand
Try to place blocks (Creative mode or otherwise)
The preview grid will start to appear glitched

### Further Information
The farther you go into higher co-ordinates the more severely the grid will break.
It happens in both, the positive and negative directions
(Speculation) Seems like an integer overflow error maybe?

**Comment by starmun-0010** [comment]
Marking as external issue for now, until I get a response from the mod authors.
